name: docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Container Image
        uses: docker/build-push-action@v3
        with:
          push: false
