name: docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
